In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
homep_df= pd.read_csv('homeprices_banglore.csv')
homep_df

area  bedrooms   price
0   1056         2   39.07
1   2600         4  120.00
2   1440         3   62.00
3   1521         3   75.00
4   1200         2   51.00
5   1170         2   38.00
6   2732         4  135.00
7   3300         4  155.00
8   1310         3   50.00
9   3700         5  167.00
10  1800         3   82.00
11  2785         4  140.00
12  1000         2   38.00
13  1100         2   40.00
14  2250         3  101.00
15  1175         2   42.00
16  1180         3   48.00
17  1540         3   60.00
18  2770         3  102.00
19   800         1   32.00

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
sX= MinMaxScaler()
sy= MinMaxScaler()

In [6]:
scaled_X= sX.fit_transform(homep_df.drop('price',axis= 'columns'))
scaled_X

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [7]:
scaled_y= sy.fit_transform(homep_df['price'].values.reshape(homep_df.shape[0],1))
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [18]:
np.dot(1,scaled_X.T)

array([[0.08827586, 0.62068966, 0.22068966, 0.24862069, 0.13793103,
        0.12758621, 0.6662069 , 0.86206897, 0.17586207, 1.        ,
        0.34482759, 0.68448276, 0.06896552, 0.10344828, 0.5       ,
        0.12931034, 0.13103448, 0.25517241, 0.67931034, 0.        ],
       [0.25      , 0.75      , 0.5       , 0.5       , 0.25      ,
        0.25      , 0.75      , 0.75      , 0.5       , 1.        ,
        0.5       , 0.75      , 0.25      , 0.25      , 0.5       ,
        0.25      , 0.5       , 0.5       , 0.5       , 0.        ]])

In [52]:
def batch_Gradient_descent(X,y_true, epochs, learning_rate= 0.01):
    
    no_of_feat = X.shape[1]
    w = np.ones(shape=(no_of_feat))
    bias=0
    
    total_samples = X.shape[0] 
    
    cost_list=[]
    epoch_list=[]
    
    for i in range(epochs):
        
        y_pred = np.dot(w,scaled_X.T) + bias
        
        w_grad = -(2/total_samples)*(X.T.dot(y_true-y_pred))
        b_grad = -(2/total_samples)*np.sum(y_true-y_pred)
                    
        w = w - learning_rate * w_grad 
        bias = bias - learning_rate * b_grad
        
        cost = np.mean(np.square(y_true-y_pred))
                   
        if i%10==0:
            cost_list.append(cost)
            epoch_list.append(epochs)
    return w, bias, cost, cost_list, epoch_list
                   

                   
                   

In [53]:
w, bias, cost, cost_list, epoch_list = batch_Gradient_descent(scaled_X,scaled_y.reshape(scaled_y.shape[0],1), 500)


ValueError: operands could not be broadcast together with shapes (2,) (2,20) 

In [31]:
w, bias, cost

NameError: name 'w' is not defined

In [40]:
homep_df.shape[0]

20